language: node_js
node_js:
    - "8"
cache:
    yarn: true
before-script:
    - yarn install
script:
    - yarn lint
before_deploy:
    - npm run build
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_KEY"
    skip_cleanup: true
    on:
        branch: master
